### ISSUE TITLE
Failing tests on python 3.9

### ISSUE THREAD

**Issue by Tishka17** [Tishka17/dataclass_factory#108]

**Comment by akernelpanicv** [comment]
Do you mean DeprecationWarning?

**Comment by Tishka17** [comment]
> Do you mean DeprecationWarning?

I mean, that in 3.9 `List` has `__origin__` and does not have `__parameters__` 

Also `TypedDict` now is not class, but function

**Comment by Tishka17** [comment]
For TypedDict it is possible to get `_TypedDcitMeta` not with retrieving `type` of `TypedDict` but of its subclass

**Comment by Tishka17** [comment]
For List it is possible to check `_nparams` / `__parameters__`  + `__origin__`
