### ISSUE TITLE
Плохое логирование ошибок для Union/Optional

### ISSUE THREAD

**Issue by tarrac79** [Tishka17/dataclass_factory#109]
Не адекватно работает Union 

```python
@dataclass
class Response(Generic[RT]):
    result: Optional[ResponseResult]
    data: Optional[RT] = None
```
Ошибка
`Invalid data at path [data]: No suitable parsers in union found for`

```python
@dataclass
class Response(Generic[RT]):
    result: Optional[ResponseResult]
    data: RT = None
```

Ошибка
`Invalid data at path [shaper_id, 0, data]: data type is not <class 'str'>`

**Comment by Tishka17** [comment]
Предлагается 
1. Union[None, X] принудительно превращать в Optional
2. Собирать текст ошибки Union из  текстов породивших ошибок с указнием типов!

**Comment by Tishka17** [comment]
Union[x, None] теперь парсится реально как Optional[x] с соответствующиим выводом ошибки
Union[a,b,c] выводит все породившие ошибки без трейса
