### ISSUE TITLE
Поддержать работу с спецсимволами

### ISSUE THREAD

**Issue by artemzdor** [Tishka17/dataclass_factory#12]
node.js возвращает поля с спецсимволами "foo-bar$1"
былобы удобно обьявить поле value_1 а получать значения из value-1

**Comment by Tishka17** [comment]
Идея.
Глобальная настройка:
1. Обрезать ли _ в конце
2. Как преобразовывать имена: camelCase, UpperCamelCase, snake_case, kebab-case

Настройка под каждый класс:
1. Обрезать ли _ в конце
2. Тип преобразования имен
3. Кастомная карта имен

Примерно так
```python
class_settings = {
    MyClass: ParserConfig(
        trim_trailing_underscore=True, 
        naming_style=NamingStyle.Kebab
    ),
    OtherClass: ParserConfig(attributes={
        "my_var": "my_var$1",
        "other": "Other",
        "something_else": "XXX"
    }
}
```

**Comment by Tishka17** [comment]
В случе указания naming_style будет возможна например такая конвертация:

```python
@dataclass
class A:
   var_name: int
   other_var: str

data = {
   "var-name": 1,
   "other-var": 2
}

parser = ParserFactory(naming_style=NamingStyle.Kebab).get_parser(A)
a = parser(data)
```

Смешение стилей не предусматривается, но возможно сочетать naming style и кастомный маппинг имен

**Comment by Tishka17** [comment]
В питоновских классах предполагаю использование только одного стиля (snake_case) - как рекомендовано в pep8. Стиль в словаре будет настраиваться

**Comment by Tishka17** [comment]
В версии 1.1.0 сделана поддержка `name_styles` как при парсинге, так и при сериализации. См. README

**Comment by Tishka17** [comment]
Done in 2.0
