### ISSUE TITLE
factory does not preserve order of dataclass declaration

### ISSUE THREAD

**Issue by VdeJong** [Tishka17/dataclass_factory#124]
I would expect the dataclass factory to preserve the order of the declared dataclass.

**Comment by Tishka17** [comment]
Can you, please, provide some example? Not sure that I understand what you mean

**Comment by VdeJong** [comment]
Factory example

```
factory = Factory(
    debug_path=True,
    default_schema=Schema(omit_default=True),
    schemas={
        SEMrushDomainRank: Schema(pre_parse=pre_parse),
        SEMrushDomainOrganicOrganic: Schema(pre_parse=pre_parse)
    }
)
```

**Comment by VdeJong** [comment]
> Can you, please, provide some example? Not sure that I understand what you mean

My bad, something else went wrong. I thought the order of the dataclass fields was not preserved when load/dumping data

**Comment by Tishka17** [comment]
I am not sure what are your expectations. Fields are parsed and dumped in unknown order. Then `__init__` will receive them with names. Also if you are using json it does not really preserve order of fields. 

If you can provide some example why you really need certain order of parsing fields i'll try to make some guaranties
