### ISSUE TITLE
Deny serialization via vars() of classes without __dict__

### ISSUE THREAD

**Issue by zhPavel** [Tishka17/dataclass_factory#126]

**Comment by Tishka17** [comment]
What is expected behaviour? Some kind of exception?

**Comment by zhPavel** [comment]
Yes, that factory can not create serializer of the class. 
Now if past attempts to create serializer failed and factory created serializer via vars() of class that had not __dict__ , serializer (not factory) would failed with obscure exception. 
Maybe we can add case of serialization of class that has __slots__.
