### ISSUE TITLE
Class systems with circular references

### ISSUE THREAD

**Issue by andrievskya** [Tishka17/dataclass_factory#144]
Может ли библиотека работать с классами с циклическиим зависимостями?
Простейший пример:

```python
@dataclass
class A:
    id: str = None
    a: "A" = None


def test():
    a_js = json.loads('{"id":"_a", "a":"_a"}')
    a : A = Factory().load(a_js, A)

```

**Comment by Tishka17** [comment]
Она может работать со структурами содержащими элементы своего типа, но она не умеет резолвить циклические ссылки и работать с объектами содержащими себя же.

https://github.com/Tishka17/dataclass_factory/blob/develop/tests/test_cycle.py
