### ISSUE TITLE
Leave None type as it is.

### ISSUE THREAD

**Issue by jjuu** [Tishka17/dataclass_factory#30]
I have a dataclass which str item default is "a" and int item default is 2.

But in data dict, their value is None.

When I call factory.load(data, DataClass), I want to leave the None type as it is, don't change it.
Or I don't want to get an exception when type .

Any solution?
Thanks

**Comment by Tishka17** [comment]
Can you provide an example? 

Bahavior depends on type annotation. `a: Optional[int]` allows `None`, but `a: int` cannot store `None` and an exception is raised.

**Comment by jjuu** [comment]
That's exactly what you are talking about.
If `a: int` raise exception but `a: Optional[int]` allows `None`.
We decided to use `a: Optional[int]`, although a little strange.

**Comment by Tishka17** [comment]
> It's exactly what you are talking about.
> If `a: int` raise exception but `a: Optional[int]` allows `None`.
> We decided to use `a: Optional[int]`, though a little strange.

Can you provide some info why do you thinks it is strange? The idea of `Optional[T]` annotation is to allow value to be either `Nonetype` or `T`: https://www.python.org/dev/peps/pep-0484/#union-types

**Comment by jjuu** [comment]
Well, I think that cause there's no definite description or I haven't found any.
We find this in the internal code.
