### ISSUE TITLE
Setting Optional fields to None by default

### ISSUE THREAD

**Issue by kvxmmu** [Tishka17/dataclass_factory#94]
Problem:

```python3
@dataclass
class TestDataclass:
    some_field: str
    some_optional_field: Optional[str] = None

@dataclass
class Test(Dataclass):
 new_field: str # syntax error

```

**Comment by Tishka17** [comment]
it normal behavior of python datclasses. My library does not implement this, it just creates instances of your classes with some data from dicts

**Comment by kvxmmu** [comment]
I'm talking about implementing extra option that can set Optional fields to None (or any other value) by default during loading data to a class

**Comment by Tishka17** [comment]
Sorry, what do you mean?
I cannot fix syntax error in provided example, becase it is python built-in behaviour.

**Comment by kvxmmu** [comment]
You don't need to fix a syntax error, see this example:
```python3

@dataclass
class TestClass:
 optional_field: Optional[int]
 x: int

data = {'x': 1}
factory.load(data, TestClass)  # possible output: TestClass(optional_field=None, x=1)```

**Comment by Tishka17** [comment]
i'm not sure i need this feature at librabry level (because you can have normal defaults)

Nevertheless, at current version you can create schema for you type with `pre_parse`:
```python
class Schema:
   def pre_parse(self, data):
      data.setdefault("optional_field", None)
      return data
```
